apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ellyofreitas/authservice
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4501
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv-clusterip
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 4501
      targetPort: 4501
