apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deploy
spec:
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: ellyofreitas/productservice
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4500
---
apiVersion: v1
kind: Service
metadata:
  name: product-srv-clusterip
spec:
  selector:
    app: learning-microservices
  ports:
    - name: product
      protocol: TCP
      port: 4500
      targetPort: 4500
